#!/usr/bin/env python3
"""Validate JinguiSSL capability, evidence, and public-document coverage."""

from __future__ import annotations

import argparse
import fnmatch
import glob
import json
import re
import subprocess
import sys
from pathlib import Path


STATUS_MEANINGS = {
    "production-candidate-with-limits": "实现和本地测试较完整，但仍保留认证、平台、互操作或时序边界。",
    "implemented-local-test": "已实现并通过本地测试，外部互操作或完整产品证明仍不足。",
    "internal-or-placeholder": "内部支撑、能力探测或储备接口，不是完整产品承诺。",
    "blocked-or-deferred": "仍有材料、平台、依赖或明确后续包阻塞。",
    "legacy-only": "仅用于旧数据或旧系统兼容，不作为现代默认方案。",
}

PUBLIC_DECLARATION = re.compile(r"^\s*public\b", re.MULTILINE)
PUBLIC_DECLARATION_START = re.compile(r"^\s*public\b")
PUBLIC_ENUM_START = re.compile(r"^\s*public\s+enum\b")
ENUM_CASE_START = re.compile(r"^\s*\|")


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)


def run_git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args], cwd=root, text=True, capture_output=True, check=False
    )


def matches(path: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatchcase(path, pattern) for pattern in patterns)


def matched_files(root: Path, patterns: list[str]) -> list[str]:
    found: set[str] = set()
    for pattern in patterns:
        for candidate in glob.glob(str(root / pattern), recursive=True):
            path = Path(candidate)
            if path.is_file():
                found.add(path.relative_to(root).as_posix())
    return sorted(found)


def normalized_code(text: str) -> str:
    return " ".join(text.split())


def declaration_header(lines: list[str], start: int) -> tuple[str, int]:
    parts: list[str] = []
    paren_depth = 0
    bracket_depth = 0
    index = start
    while index < len(lines):
        code = lines[index].split("//", 1)[0].strip()
        if code:
            header = code.split("{", 1)[0].strip()
            if header:
                parts.append(header)
            paren_depth += code.count("(") - code.count(")")
            bracket_depth += code.count("[") - code.count("]")
            if "{" in code:
                break
            if (
                paren_depth <= 0
                and bracket_depth <= 0
                and not code.endswith((",", "&"))
            ):
                break
        index += 1
    return normalized_code(" ".join(parts)), index


def public_surface_fingerprint(text: str) -> list[str]:
    lines = text.splitlines()
    surface: list[str] = []
    public_enum_depths: list[int] = []
    brace_depth = 0
    index = 0

    while index < len(lines):
        code = lines[index].split("//", 1)[0]
        stripped = code.strip()

        if public_enum_depths and brace_depth == public_enum_depths[-1]:
            if ENUM_CASE_START.match(code):
                case, case_end = declaration_header(lines, index)
                surface.append(f"enum-case:{case}")
                index = case_end
                code = lines[index].split("//", 1)[0]
                stripped = code.strip()

        if PUBLIC_DECLARATION_START.match(code):
            header, header_end = declaration_header(lines, index)
            surface.append(f"declaration:{header}")
            if PUBLIC_ENUM_START.match(code):
                opening_depth = brace_depth
                for header_line in lines[index : header_end + 1]:
                    opening_depth += header_line.count("{") - header_line.count("}")
                if opening_depth > brace_depth:
                    public_enum_depths.append(opening_depth)

        brace_depth += stripped.count("{") - stripped.count("}")
        while public_enum_depths and brace_depth < public_enum_depths[-1]:
            public_enum_depths.pop()
        index += 1

    return sorted(surface)


def markdown_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def markdown_links(paths: list[str]) -> str:
    links = []
    for path in paths:
        target = path[5:] if path.startswith("docs/") else f"../{path}"
        links.append(f"[`{Path(path).name}`]({target})")
    return "<br>".join(links)


def render_matrix(manifest: dict) -> str:
    lines = [
        f"# {manifest['repository']} Capability Matrix",
        "",
        "<!-- Generated by scripts/jinguissl_capability_gate.py. Edit docs/capabilities.json instead. -->",
        "",
        "这张表用于在准备 MR/PR 前核对公开能力、测试证据、README 与使用手册。",
        "状态描述的是当前证据强度，不是法律认证、安全认证或发布承诺。",
        "",
        "## Status Vocabulary",
        "",
        "| Status | Meaning |",
        "| --- | --- |",
    ]
    for status, meaning in STATUS_MEANINGS.items():
        lines.append(f"| `{status}` | {meaning} |")

    lines.extend(
        [
            "",
            "## Capabilities",
            "",
            "| Capability | Status | Public surface | Evidence | Manual | Current limit |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for capability in manifest["capabilities"]:
        lines.append(
            "| `{id}` {label} | `{status}` | {summary} | {proof} | {manual} | {limits} |".format(
                id=capability["id"],
                label=markdown_cell(capability["label"]),
                status=capability["status"],
                summary=markdown_cell(capability["summary"]),
                proof=markdown_cell(capability["proof"]),
                manual=markdown_links(capability["manualPages"]),
                limits=markdown_cell(capability["limits"]),
            )
        )

    lines.extend(
        [
            "",
            "## Pre-Review Check",
            "",
            "```bash",
            "bash scripts/jinguissl_pre_review.sh <base-ref>",
            "```",
            "",
            "省略 `<base-ref>` 时仍会检查清单结构、公开文件归类和生成文档一致性；",
            "提供 base ref 时，还会检查 public API 变化是否同步了能力清单、生成矩阵、README 和至少一页对应 manual。",
            "",
        ]
    )
    return "\n".join(lines)


def validate_manifest(root: Path, manifest: dict) -> list[str]:
    errors: list[str] = []
    if manifest.get("schemaVersion") != 1:
        errors.append("docs/capabilities.json schemaVersion must be 1")

    readme = manifest.get("readme", "README.md")
    readme_path = root / readme
    if not readme_path.is_file():
        errors.append(f"README path does not exist: {readme}")
        readme_text = ""
    else:
        readme_text = readme_path.read_text(encoding="utf-8")

    seen: set[str] = set()
    capabilities = manifest.get("capabilities", [])
    if not capabilities:
        errors.append("capabilities must not be empty")

    for capability in capabilities:
        capability_id = capability.get("id", "")
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", capability_id):
            errors.append(f"invalid capability id: {capability_id!r}")
        if capability_id in seen:
            errors.append(f"duplicate capability id: {capability_id}")
        seen.add(capability_id)

        status = capability.get("status")
        if status not in STATUS_MEANINGS:
            errors.append(f"{capability_id}: unknown status {status!r}")

        for key in ("label", "summary", "proof", "limits"):
            if not str(capability.get(key, "")).strip():
                errors.append(f"{capability_id}: {key} must not be empty")

        for key in ("sourceGlobs", "testGlobs", "readmeTokens", "manualPages"):
            if not capability.get(key):
                errors.append(f"{capability_id}: {key} must not be empty")

        if not matched_files(root, capability.get("sourceGlobs", [])):
            errors.append(f"{capability_id}: sourceGlobs match no files")
        if not matched_files(root, capability.get("testGlobs", [])):
            errors.append(f"{capability_id}: testGlobs match no files")

        for token in capability.get("readmeTokens", []):
            if token not in readme_text:
                errors.append(f"{capability_id}: README token missing: {token!r}")
        for manual in capability.get("manualPages", []):
            if not (root / manual).is_file():
                errors.append(f"{capability_id}: manual page missing: {manual}")

    public_globs = manifest.get("publicSourceGlobs", ["src/**/*.cj"])
    excludes = manifest.get("excludeSourceGlobs", [])
    for source in matched_files(root, public_globs):
        if matches(source, excludes):
            continue
        text = (root / source).read_text(encoding="utf-8")
        if not PUBLIC_DECLARATION.search(text):
            continue
        if not any(matches(source, item["sourceGlobs"]) for item in capabilities):
            errors.append(f"unclassified public source file: {source}")

    for rule in manifest.get("forbiddenPublicText", []):
        pattern = re.compile(rule["pattern"])
        for path in matched_files(root, rule["paths"]):
            for line_number, line in enumerate(
                (root / path).read_text(encoding="utf-8").splitlines(), start=1
            ):
                if pattern.search(line):
                    errors.append(
                        f"{path}:{line_number}: {rule['message']} ({line.strip()})"
                    )
    return errors


def validate_public_delta(root: Path, manifest: dict, base_ref: str) -> list[str]:
    errors: list[str] = []
    verify = run_git(root, "rev-parse", "--verify", base_ref)
    if verify.returncode != 0:
        return [f"base ref is not available: {base_ref}"]

    diff_spec = base_ref
    changed_result = run_git(root, "diff", "--name-only", diff_spec, "--")
    if changed_result.returncode != 0:
        return [changed_result.stderr.strip() or "unable to read changed files"]

    changed = {line for line in changed_result.stdout.splitlines() if line}
    untracked_result = run_git(root, "ls-files", "--others", "--exclude-standard")
    if untracked_result.returncode != 0:
        return [untracked_result.stderr.strip() or "unable to read untracked files"]
    changed.update(line for line in untracked_result.stdout.splitlines() if line)

    capabilities = manifest["capabilities"]
    excludes = manifest.get("excludeSourceGlobs", [])
    public_changed: dict[str, set[str]] = {}

    for path in sorted(changed):
        if not path.endswith(".cj") or not path.startswith("src/") or matches(path, excludes):
            continue
        current_path = root / path
        current_text = (
            current_path.read_text(encoding="utf-8") if current_path.is_file() else ""
        )
        base_result = run_git(root, "show", f"{base_ref}:{path}")
        base_text = base_result.stdout if base_result.returncode == 0 else ""
        if public_surface_fingerprint(current_text) == public_surface_fingerprint(base_text):
            continue
        owners = {
            item["id"] for item in capabilities if matches(path, item["sourceGlobs"])
        }
        if not owners:
            errors.append(f"public API changed in an unclassified file: {path}")
            continue
        for owner in owners:
            public_changed.setdefault(owner, set()).add(path)

    readme = manifest.get("readme", "README.md")
    manifest_path = "docs/capabilities.json"
    matrix_path = manifest.get("matrix", "docs/capability-matrix.md")
    by_id = {item["id"]: item for item in capabilities}
    for owner, paths in sorted(public_changed.items()):
        context = ", ".join(sorted(paths))
        if manifest_path not in changed:
            errors.append(
                f"{context}: public API changed for {owner}, but {manifest_path} was not updated"
            )
        if matrix_path not in changed:
            errors.append(
                f"{context}: public API changed for {owner}, but {matrix_path} was not updated"
            )
        if readme not in changed:
            errors.append(
                f"{context}: public API changed for {owner}, but {readme} was not updated"
            )
        if changed.isdisjoint(by_id[owner]["manualPages"]):
            errors.append(
                f"{context}: public API changed for {owner}, but no matching manual page was updated"
            )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--manifest", default="docs/capabilities.json")
    parser.add_argument("--base-ref")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    manifest_path = root / args.manifest
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot load {args.manifest}: {error}")
        return 1

    rendered = render_matrix(manifest)
    matrix_path = root / manifest.get("matrix", "docs/capability-matrix.md")
    if args.write:
        matrix_path.write_text(rendered, encoding="utf-8")

    errors = validate_manifest(root, manifest)
    if not matrix_path.is_file():
        errors.append(f"generated matrix is missing: {matrix_path.relative_to(root)}")
    elif matrix_path.read_text(encoding="utf-8") != rendered:
        errors.append("generated capability matrix is stale; run the gate with --write")
    if args.base_ref:
        errors.extend(validate_public_delta(root, manifest, args.base_ref))

    if errors:
        for message in errors:
            fail(message)
        print(f"JinguiSSL capability gate failed: {len(errors)} error(s)", file=sys.stderr)
        return 1

    print(
        f"JinguiSSL capability gate passed: {len(manifest['capabilities'])} capability row(s)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
